name: Deploy to AWS Lambda

on:
  push:
    branches: [ "run-on-lambda" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: build
      run: npx ncc build index.ts
    - name: zip
      run: zip -j deploy.zip ./dist/*
    - name: deploy
      run: aws lambda update-function-code --function-name=${{ secrets.AWS_FUNCTION_NAME }} --zip-file=fileb://deploy.zip
